name: medium
type: ddit
hidden_size: 8192
cond_dim: 256
length: 1024
n_blocks: 10
n_heads: ${div_up:${.hidden_size}, ${.cond_dim}}
scale_by_sigma: True
dropout: 0.1
tie_word_embeddings: True
adaln: False
attn_backend: flash_attn